export const GET_CITYS = "GET_CITYS";
export const SELECTED_CITY = "SELECTED_CITY";
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";
export const FILTER_BY_SURFACE = "FILTER_BY_SURFACE";
export const FILTER_BY_DELIVERED = "FILTER_BY_DELIVERED";
export const APPLY_FILTERS = "APPLY_FILTERS";
export const CLEAR_FILTER = "CLEAR_FILTER";
